services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  shop_app:
    build:
      context: ./shop_web
      dockerfile: Dockerfile
    image: shop_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwordA1!
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
