services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: app
    ports:
    - mode: ingress
      target: 8000
      published: "8888"
      protocol: tcp


  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwordA1!
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
